name:                brainfuck
version:             0.1.0.0
github:              "Berengal/brainfuck"
license:             BSD3
author:              "Sjur Gjøstein Karevoll"
maintainer:          "sjurberengal@gmail.com"
copyright:           "2019 Sjur Gjøstein Karevoll"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Berengal/brainfuck#readme>

dependencies:
- base >= 4.11 && < 5
- llvm-hs >= 8.0.0 && < 8.1
- llvm-hs-pure >= 8.0.0 && < 8.1
- containers >= 0.6.0.1 && < 0.7
- mtl >= 2.2.2 && < 2.3
- bytestring >= 0.10.8.2 && < 0.11

default-extensions:
  - NondecreasingIndentation
  
library:
  source-dirs: src

executables:
  bfi:
    main:                Interpreter
    source-dirs:         app
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - brainfuck
    - optparse-applicative >= 0.14.3.0 && <0.15
    - filepath >= 1.4.2.1 && <1.5
  bfc:
    main:                Compiler
    source-dirs:         app
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - brainfuck
    - optparse-applicative >= 0.14.3.0 && <0.15
    - filepath >= 1.4.2.1 && <1.5
    
tests:
  brainfuck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - brainfuck
