name:                brainfuck
version:             0.1.0.0
github:              "Berengal/brainfuck"
license:             BSD3
author:              "Sjur Gjøstein Karevoll"
maintainer:          "sjurberengal@gmail.com"
copyright:           "2019 Sjur Gjøstein Karevoll"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Berengal/brainfuck#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  brainfuck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XNondecreasingIndentation
    dependencies:
    - brainfuck

tests:
  brainfuck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfuck
