name:                hbfc
version:             0.1.0.0
github:              "Berengal/hbfc"
license:             GPL-3.0-only
author:              "Sjur Gjøstein Karevoll"
maintainer:          "sjurberengal@gmail.com"
copyright:           "2019 Sjur Gjøstein Karevoll"

extra-source-files:
- README.org

synopsis:            Optimizing Brainf*ck compiler
category:            Language

description:         Please see the README on GitHub at <https://github.com/Berengal/hbfc#readme>

dependencies:
- base >= 4.11 && < 5
- llvm-hs >= 8.0.0 && < 8.1
- llvm-hs-pure >= 8.0.0 && < 8.1
- containers >= 0.6.0.1 && < 0.7
- mtl >= 2.2.2 && < 2.3
- bytestring >= 0.10.8.2 && < 0.11
- process >= 1.6.5.0 && < 1.7

default-extensions:
  - NondecreasingIndentation
  - BlockArguments
  - LambdaCase
  - RecordWildCards

library:
  source-dirs: src

executables:
  hbfi:
    main:                Interpreter
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -with-rtsopts=-qg1
    dependencies:
      - hbfc
      - optparse-applicative >= 0.14.3.0 && <0.15
      - filepath >= 1.4.2.1 && <1.5

  hbfc:
    main:                Compiler
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -with-rtsopts=-qg1
    dependencies:
      - hbfc
      - optparse-applicative >= 0.14.3.0 && <0.15
      - filepath >= 1.4.2.1 && <1.5

tests:
  brainfuck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -with-rtsopts=-qg1
    dependencies:
      - hbfc
      - QuickCheck >= 2.12.6.1 && < 2.14
      - hspec >= 2.6.1 && <2.8
